### PR TITLE
Ft-trackingPark

### PR DESCRIPTION
**Pull request by kibongos40**
# Screen for Tracking park screen
This is the pull for screen for the Tracking park
image

### CODE REVIEW

**Comment by 911samuel** [comment]
great work remember to solve that conflict

**Review by 911samuel — APPROVED** [review]
great work

**Comment by Adadie** [comment]
Is this how we are now creating PRs? Plus also approving them when they have conflicts? @kibongos40  @911samuel

**Review by 911samuel — COMMENTED** [review]
i can see that you resolved the conflict but you need to the PR title

**Pull request merged**
